### ISSUE TITLE
database file missing?

### ISSUE THREAD

**Issue by santhosh0209** [HafidzN/Inschatgram#1]
MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.

i am getting this error please help me i am not familiar with MongoDb.

**Comment by HafidzN** [comment]
Hi, that is simply because i hide some information such as mongoDB uri or jwt secret in dotenv file. Absolutely you can setup your own mongodb atlas and then replace my process.env.MONGODB_URL in the backend server's App.js with your newly generated mongodb uri. I hope it solve your problem.

**Comment by santhosh0209** [comment]
Pls help me I am new to programming. I really love it project..can u send
me any tutorial video on that. I have 0percent knowledge on mongodb so no
idea about that.

**Comment by HafidzN** [comment]
This playlist [link](https://www.youtube.com/watch?v=Tt_CS-iQBqQ&list=PLB97yPrFwo5g0FQr4rqImKa55F_aPiQWk&index=5) will help you out and teach you how to build similar project like mine but far more in simpler ways for you

**Comment by santhosh0209** [comment]
Thank you so much I will try and ask you if any doubts further.

**Comment by santhosh0209** [comment]
Mam now the database issue has been solved but I got a new error when I try
to sign-up and login ..I have stated in GitHub issues. Kindly help me . I
searched for lots of instagram clone project but among that this is the
best so I need this project to work correctly please help me out. Please

Thank you
